// <auto-generated />
using System;
using FootballClubApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballClubApp.Server.Migrations
{
    [DbContext(typeof(FootballClubDbContext))]
    [Migration("20260112193104_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballClubApp.Server.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<string>("ClubCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClubLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FoundedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StadiumName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClubId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            ClubId = 1,
                            ClubCode = "MU-2025",
                            ClubLogo = "/images/clubs/manchester-united.png",
                            ClubName = "Manchester United",
                            FoundedDate = new DateTime(1878, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StadiumName = "Old Trafford"
                        },
                        new
                        {
                            ClubId = 2,
                            ClubCode = "FCB-2025",
                            ClubLogo = "/images/clubs/barcelona.png",
                            ClubName = "FC Barcelona",
                            FoundedDate = new DateTime(1899, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StadiumName = "Camp Nou"
                        },
                        new
                        {
                            ClubId = 3,
                            ClubCode = "RM-2025",
                            ClubLogo = "/images/clubs/real-madrid.png",
                            ClubName = "Real Madrid",
                            FoundedDate = new DateTime(1902, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StadiumName = "Santiago Bernabéu"
                        });
                });

            modelBuilder.Entity("FootballClubApp.Server.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlayerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlayerPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.HasIndex("ClubId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            ClubId = 1,
                            DateOfBirth = new DateTime(1985, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JerseyNumber = 7,
                            Nationality = "Portugal",
                            PlayerCode = "CR7-2025",
                            PlayerName = "Cristiano Ronaldo",
                            PlayerPhoto = "/images/players/ronaldo.jpg"
                        },
                        new
                        {
                            PlayerId = 2,
                            ClubId = 2,
                            DateOfBirth = new DateTime(1987, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JerseyNumber = 10,
                            Nationality = "Argentina",
                            PlayerCode = "LM10-2025",
                            PlayerName = "Lionel Messi",
                            PlayerPhoto = "/images/players/messi.jpg"
                        },
                        new
                        {
                            PlayerId = 3,
                            ClubId = 2,
                            DateOfBirth = new DateTime(1992, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JerseyNumber = 11,
                            Nationality = "Brazil",
                            PlayerCode = "NJR11-2025",
                            PlayerName = "Neymar Jr",
                            PlayerPhoto = "/images/players/neymar.jpg"
                        });
                });

            modelBuilder.Entity("FootballClubApp.Server.Models.PlayerDetail", b =>
                {
                    b.Property<int>("PlayerDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerDetailId"));

                    b.Property<decimal>("AnnualSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<DateTime>("ContractEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoalsScored")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("PlayerDetailId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PositionId");

                    b.ToTable("PlayerDetails");

                    b.HasData(
                        new
                        {
                            PlayerDetailId = 1,
                            AnnualSalary = 50000000m,
                            Assists = 45,
                            ContractEnd = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStart = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoalsScored = 145,
                            MatchesPlayed = 200,
                            PlayerId = 1,
                            PositionId = 8
                        },
                        new
                        {
                            PlayerDetailId = 2,
                            AnnualSalary = 55000000m,
                            Assists = 305,
                            ContractEnd = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStart = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoalsScored = 672,
                            MatchesPlayed = 778,
                            PlayerId = 2,
                            PositionId = 6
                        },
                        new
                        {
                            PlayerDetailId = 3,
                            AnnualSalary = 45000000m,
                            Assists = 237,
                            ContractEnd = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStart = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoalsScored = 436,
                            MatchesPlayed = 649,
                            PlayerId = 3,
                            PositionId = 7
                        });
                });

            modelBuilder.Entity("FootballClubApp.Server.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            Description = "Defends the goal",
                            PositionName = "Goalkeeper (GK)"
                        },
                        new
                        {
                            PositionId = 2,
                            Description = "Central defender",
                            PositionName = "Defender (CB)"
                        },
                        new
                        {
                            PositionId = 3,
                            Description = "Left side defender",
                            PositionName = "Left Back (LB)"
                        },
                        new
                        {
                            PositionId = 4,
                            Description = "Right side defender",
                            PositionName = "Right Back (RB)"
                        },
                        new
                        {
                            PositionId = 5,
                            Description = "Central midfielder",
                            PositionName = "Midfielder (CM)"
                        },
                        new
                        {
                            PositionId = 6,
                            Description = "Creative playmaker",
                            PositionName = "Attacking Midfielder (CAM)"
                        },
                        new
                        {
                            PositionId = 7,
                            Description = "Side attacker",
                            PositionName = "Winger (LW/RW)"
                        },
                        new
                        {
                            PositionId = 8,
                            Description = "Forward, main goal scorer",
                            PositionName = "Striker (ST)"
                        });
                });

            modelBuilder.Entity("FootballClubApp.Server.Models.Player", b =>
                {
                    b.HasOne("FootballClubApp.Server.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FootballClubApp.Server.Models.PlayerDetail", b =>
                {
                    b.HasOne("FootballClubApp.Server.Models.Player", "Player")
                        .WithMany("PlayerDetails")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballClubApp.Server.Models.Position", "Position")
                        .WithMany("PlayerDetails")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("FootballClubApp.Server.Models.Club", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FootballClubApp.Server.Models.Player", b =>
                {
                    b.Navigation("PlayerDetails");
                });

            modelBuilder.Entity("FootballClubApp.Server.Models.Position", b =>
                {
                    b.Navigation("PlayerDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
